#!/bin/bash
docker build -t slackin-swift-run .
docker build -t slackin-swift-build -f Dockerfile-tools .
docker run -v $PWD:/root/project -w /root/project slackin-swift-build /swift-utils/tools-utils.sh build release
docker run -it -p 8080:8080 -v $PWD:/root/project -w /root/project slackin-swift-run sh -c ".build-ubuntu/release/slackin-swift $1"
