#!/bin/bash
docker build -t slackin-swift-build -f Dockerfile-tools .
docker run -v $PWD:/swift-project -w /swift-project slackin-swift-build /swift-utils/tools-utils.sh build release
docker build -t slackin-swift --build-arg SLACK_TOKEN=$1 .
docker run -p 8080:8080 slackin-swift